/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'text-primary': '#18181B',
        'state-skipped-neutral': '#E4E4E7',
        'surface-bright': '#fbf8fc',
        'canvas-bg': '#F5F5F7',
        background: '#fbf8fc',
        'on-tertiary-fixed': '#23005c',
        'inverse-primary': '#abd600',
        'on-surface': '#1b1b1e',
        'on-surface-variant': '#444933',
        'secondary-fixed-dim': '#c5c5d2',
        'surface-variant': '#e4e1e6',
        'accent-terracotta-text': '#C2410C',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#f2e9ff',
        'on-secondary-fixed-variant': '#454650',
        'outline-variant': '#c4c9ac',
        surface: '#fbf8fc',
        'border-subtle': '#F0F0F2',
        'surface-card': '#FFFFFF',
        'error-container': '#ffdad6',
        primary: '#506600',
        'accent-mint-text': '#047857',
        'on-error': '#ffffff',
        secondary: '#5c5e68',
        'inverse-on-surface': '#f3f0f4',
        'primary-container': '#ccff00',
        'on-primary-container': '#5b7300',
        'on-error-container': '#93000a',
        'tertiary-fixed': '#e9ddff',
        'on-primary-fixed': '#161e00',
        'surface-container-low': '#f6f2f7',
        'surface-container-high': '#eae7eb',
        'text-muted': '#A1A1AA',
        'on-secondary': '#ffffff',
        'inverse-surface': '#303033',
        'tertiary-fixed-dim': '#d0bcff',
        'primary-fixed-dim': '#abd600',
        'on-secondary-fixed': '#191b24',
        'accent-lime-dim': '#D4F638',
        'accent-lavender': '#EDE9FE',
        'border-dark-subtle': '#2A2D3A',
        'surface-dim': '#dcd9dd',
        'secondary-fixed': '#e1e1ee',
        'sidebar-card': '#21232D',
        'accent-terracotta': '#FFEDD5',
        'on-tertiary': '#ffffff',
        'text-secondary': '#71717A',
        'on-tertiary-fixed-variant': '#5516be',
        'accent-lime': '#CCFF00',
        'accent-lavender-text': '#6D28D9',
        'on-primary': '#ffffff',
        'sidebar-dark': '#16171D',
        error: '#ba1a1a',
        'accent-mint': '#D1FAE5',
        outline: '#747a60',
        'on-tertiary-container': '#7a49e4',
        'surface-container-highest': '#e4e1e6',
        'on-background': '#1b1b1e',
        'primary-fixed': '#c3f400',
        'surface-tint': '#506600',
        'secondary-container': '#e1e1ee',
        'surface-container': '#f0edf1',
        'on-secondary-container': '#62646e',
        tertiary: '#6d3bd7',
        'on-primary-fixed-variant': '#3c4d00',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        margin: '2rem',
        'space-xl': '2rem',
        'space-sm': '0.5rem',
        gutter: '1.5rem',
        'space-md': '1rem',
        'margin-mobile': '1rem',
        'gutter-mobile': '1rem',
        'space-lg': '1.5rem',
      },
      transitionTimingFunction: {
        spring: 'cubic-bezier(0.32, 0.72, 0, 1)',
        'out-soft': 'cubic-bezier(0.22, 1, 0.36, 1)',
      },
      keyframes: {
        'fade-up': { from: { opacity: '0', transform: 'translateY(14px)' }, to: { opacity: '1', transform: 'none' } },
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'scale-in': { from: { opacity: '0', transform: 'scale(0.94)' }, to: { opacity: '1', transform: 'none' } },
        'slide-up': { from: { opacity: '0', transform: 'translateY(24px)' }, to: { opacity: '1', transform: 'none' } },
        pop: { '0%': { transform: 'scale(0.6)' }, '55%': { transform: 'scale(1.18)' }, '100%': { transform: 'scale(1)' } },
        'ring-pulse': { '0%': { transform: 'scale(1)', opacity: '0.55' }, '100%': { transform: 'scale(1.9)', opacity: '0' } },
        float: { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-6px)' } },
        flame: {
          '0%, 100%': { transform: 'scale(1) rotate(-2deg)' },
          '50%': { transform: 'scale(1.1) rotate(2deg)' },
        },
      },
      animation: {
        'fade-up': 'fade-up 0.6s cubic-bezier(0.32, 0.72, 0, 1) backwards',
        'fade-in': 'fade-in 0.4s cubic-bezier(0.22, 1, 0.36, 1) backwards',
        'scale-in': 'scale-in 0.35s cubic-bezier(0.32, 0.72, 0, 1) backwards',
        'slide-up': 'slide-up 0.5s cubic-bezier(0.32, 0.72, 0, 1) backwards',
        pop: 'pop 0.45s cubic-bezier(0.32, 0.72, 0, 1)',
        'ring-pulse': 'ring-pulse 0.7s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        float: 'float 4s ease-in-out infinite',
        flame: 'flame 1.8s ease-in-out infinite',
      },
      fontFamily: {
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-xl': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        caption: ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-xl-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['22px', { lineHeight: '30px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '26px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'headline-xl-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
