/** @type {import('tailwindcss').Config} */
/** Theme-aware colours read a CSS variable (see globals.css) so `.dark` can swap them. */
const v = (name) => `rgb(var(--c-${name}) / <alpha-value>)`;

module.exports = {
  content: ['./app/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'text-primary': v('text-primary'),
        'state-skipped-neutral': '#E4E4E7',
        'surface-bright': v('surface-bright'),
        'canvas-bg': v('canvas-bg'),
        background: v('background'),
        'on-tertiary-fixed': '#23005c',
        'inverse-primary': '#abd600',
        'on-surface': v('on-surface'),
        'on-surface-variant': v('on-surface-variant'),
        'secondary-fixed-dim': '#c5c5d2',
        'surface-variant': v('surface-variant'),
        'accent-terracotta-text': v('accent-terracotta-text'),
        'surface-container-lowest': v('surface-container-lowest'),
        'tertiary-container': '#f2e9ff',
        'on-secondary-fixed-variant': '#454650',
        'outline-variant': v('outline-variant'),
        surface: v('surface'),
        'border-subtle': v('border-subtle'),
        'surface-card': v('surface-card'),
        'error-container': v('error-container'),
        primary: v('primary'),
        'accent-mint-text': v('accent-mint-text'),
        'on-error': '#ffffff',
        secondary: v('secondary'),
        'inverse-on-surface': '#f3f0f4',
        'primary-container': '#ccff00',
        'on-primary-container': '#5b7300',
        'on-error-container': v('on-error-container'),
        'tertiary-fixed': '#e9ddff',
        'on-primary-fixed': '#161e00',
        'surface-container-low': v('surface-container-low'),
        'surface-container-high': v('surface-container-high'),
        'text-muted': v('text-muted'),
        'on-secondary': '#ffffff',
        'inverse-surface': '#303033',
        'tertiary-fixed-dim': '#d0bcff',
        'primary-fixed-dim': '#abd600',
        'on-secondary-fixed': '#191b24',
        'accent-lime-dim': '#D4F638',
        'accent-lavender': v('accent-lavender'),
        'border-dark-subtle': '#2A2D3A',
        'surface-dim': '#dcd9dd',
        'secondary-fixed': '#e1e1ee',
        'sidebar-card': '#21232D',
        'accent-terracotta': v('accent-terracotta'),
        'on-tertiary': '#ffffff',
        'text-secondary': v('text-secondary'),
        'on-tertiary-fixed-variant': '#5516be',
        'accent-lime': '#CCFF00',
        'accent-lavender-text': v('accent-lavender-text'),
        'on-primary': '#ffffff',
        'sidebar-dark': '#16171D',
        error: v('error'),
        'accent-mint': v('accent-mint'),
        outline: v('outline'),
        'on-tertiary-container': '#7a49e4',
        'surface-container-highest': v('surface-container-highest'),
        'on-background': v('on-background'),
        'primary-fixed': '#c3f400',
        'surface-tint': '#506600',
        'secondary-container': '#e1e1ee',
        'surface-container': v('surface-container'),
        'on-secondary-container': '#62646e',
        tertiary: v('tertiary'),
        'on-primary-fixed-variant': '#3c4d00',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        margin: '2rem',
        'space-xl': '2rem',
        'space-sm': '0.5rem',
        gutter: '1.5rem',
        'space-md': '1rem',
        'margin-mobile': '1rem',
        'gutter-mobile': '1rem',
        'space-lg': '1.5rem',
      },
      boxShadow: {
        soft: '0 1px 2px rgba(80, 102, 0, 0.04), 0 8px 24px -8px rgba(80, 102, 0, 0.1)',
        lift: '0 2px 4px rgba(80, 102, 0, 0.05), 0 18px 36px -12px rgba(80, 102, 0, 0.18)',
      },
      transitionTimingFunction: {
        spring: 'cubic-bezier(0.32, 0.72, 0, 1)',
        'out-soft': 'cubic-bezier(0.22, 1, 0.36, 1)',
      },
      keyframes: {
        'fade-up': { from: { opacity: '0', transform: 'translateY(14px)' }, to: { opacity: '1', transform: 'none' } },
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'scale-in': { from: { opacity: '0', transform: 'scale(0.94)' }, to: { opacity: '1', transform: 'none' } },
        'slide-up': { from: { opacity: '0', transform: 'translateY(24px)' }, to: { opacity: '1', transform: 'none' } },
        pop: { '0%': { transform: 'scale(0.6)' }, '55%': { transform: 'scale(1.18)' }, '100%': { transform: 'scale(1)' } },
        'ring-pulse': { '0%': { transform: 'scale(1)', opacity: '0.55' }, '100%': { transform: 'scale(1.9)', opacity: '0' } },
        float: { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-6px)' } },
        'grow-x': { from: { transform: 'scaleX(0)' } },
        'grow-y': { from: { transform: 'scaleY(0)' }, to: { transform: 'scaleY(1)' } },
        wave: {
          '0%, 60%, 100%': { transform: 'rotate(0)' },
          '10%, 30%': { transform: 'rotate(14deg)' },
          '20%, 40%': { transform: 'rotate(-8deg)' },
          '50%': { transform: 'rotate(10deg)' },
        },
        flame: {
          '0%, 100%': { transform: 'scale(1) rotate(-2deg)' },
          '50%': { transform: 'scale(1.1) rotate(2deg)' },
        },
      },
      animation: {
        'fade-up': 'fade-up 0.6s cubic-bezier(0.32, 0.72, 0, 1) backwards',
        'fade-in': 'fade-in 0.4s cubic-bezier(0.22, 1, 0.36, 1) backwards',
        'scale-in': 'scale-in 0.35s cubic-bezier(0.32, 0.72, 0, 1) backwards',
        'slide-up': 'slide-up 0.5s cubic-bezier(0.32, 0.72, 0, 1) backwards',
        pop: 'pop 0.45s cubic-bezier(0.32, 0.72, 0, 1)',
        'ring-pulse': 'ring-pulse 0.7s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        float: 'float 4s ease-in-out infinite',
        'grow-x': 'grow-x 0.9s cubic-bezier(0.32, 0.72, 0, 1) 0.15s backwards',
        'grow-y': 'grow-y 0.8s cubic-bezier(0.32, 0.72, 0, 1) backwards',
        wave: 'wave 2.2s ease-in-out 0.6s 1',
        flame: 'flame 1.8s ease-in-out infinite',
      },
      fontFamily: {
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-xl': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        caption: ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-xl-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['22px', { lineHeight: '30px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '26px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'headline-xl-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
